'use client';
import {useEffect,useState,useRef} from 'react';
import {ShopHeader,ShopFooter} from './shop-frame';
import {defaultContent as content} from '@/lib/content';
import {demoListings,loadListings,formatPrice,type Listing} from '@/lib/catalog';

function Card({item}:{item:Listing}){return <article className="listing-card"><a className="listing-media demo-media" href={'/listing/'+item.id}><img src={item.image} alt={item.title} loading="lazy"/></a><h3 className="listing-name"><a href={'/listing/'+item.id}>{item.title}</a></h3><div className="listing-prices"><strong>{formatPrice(item.price)}</strong></div><span className="muted">{item.category}</span><div className="listing-platforms"><a href={'/listing/'+item.id}>Discover this gift →</a></div></article>}
function Carousel({children,label}:{children:React.ReactNode;label:string}){const track=useRef<HTMLDivElement>(null);return <div className="demo-carousel" role="region" aria-label={label}><div className="demo-track" ref={track}>{children}</div><div className="demo-controls"><button aria-label={'Previous '+label} onClick={()=>track.current?.scrollBy({left:-track.current.clientWidth,behavior:'smooth'})}>←</button><button aria-label={'Next '+label} onClick={()=>track.current?.scrollBy({left:track.current.clientWidth,behavior:'smooth'})}>→</button></div></div>}
export default function Storefront({page='home',id}:{page?:'home'|'collection'|'contact'|'wholesale'|'policies'|'listing';id?:string}){
 const [items,setItems]=useState(demoListings),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('featured'),[ready,setReady]=useState(false);
 useEffect(()=>{setItems(loadListings());const params=new URLSearchParams(window.location.search);setQuery(params.get('q')||'');setCategory(params.get('category')||'');setReady(true);},[]);
 const visible=items.filter(i=>i.published);const filtered=visible.filter(i=>(!category||i.category===category)&&`${i.title} ${i.description}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0);
 const item=visible.find(i=>i.id===id);
 return <><ShopHeader content={content}/><div className="demo-notice">Frontend preview · Sample products · No orders or messages are sent</div>
 {page==='home'?<main className="shop"><section className="intro banner demo-hero"><div><p className="eyebrow">THE ART OF GIVING</p><h1>{content.bannerTitle}</h1><p>{content.bannerText}</p><a className="primary banner-button" href="/collection">Explore the collection →</a></div><img src="/demo/gift-3.svg" alt="An illustrated gift wrapped with a ribbon"/></section><section id="categories" className="collection"><p className="eyebrow">SOMETHING FOR EVERY OCCASION</p><h2>Shop by category</h2><Carousel label="categories">{content.categories.map(c=><a className="category-card" href={'/collection?category='+encodeURIComponent(c.name)} key={c.id}><img src={c.image} alt={c.name}/><h3>{c.name}</h3></a>)}</Carousel></section><section id="best-sellers" className="collection"><div className="section-top"><div><p className="eyebrow">THOUGHTFUL FAVORITES</p><h2>Best sellers</h2></div><a href="/collection">View collections →</a></div><Carousel label="products">{visible.map(i=><Card item={i} key={i.id}/>)}</Carousel></section><section className="testimonials collection"><p className="eyebrow">A LITTLE KINDNESS GOES A LONG WAY</p><h2>Thoughtful gifts. Beautiful moments.</h2><p className="muted">Personal touches, handcrafted details, and something for every occasion.</p><div className="demo-values"><div><span>♡</span><h3>Made personal</h3><p>Small details that mean the world.</p></div><div><span>✧</span><h3>Inspired by artisans</h3><p>Discover the beauty in thoughtful craft.</p></div><div><span>◇</span><h3>For every moment</h3><p>Celebrate the everyday and the extraordinary.</p></div></div></section><section className="find-us collection"><p className="eyebrow">LET’S STAY CONNECTED</p><h2>Find us</h2><p>Explore more gifts, inspiration, and updates from GiftsByArtisans.</p><a className="banner-button primary" href="/contact">Get in touch</a></section></main>:
 page==='collection'?<main className="shop"><section className="collection"><p className="eyebrow">CURATED WITH CARE</p><h1 className="catalog-heading">Collections</h1><div className="catalog-filters"><label>Search gifts<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles or descriptions…"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{content.categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><p className="muted" role="status">{filtered.length} gifts{query&&` matching “${query}”`}</p>{filtered.length?<div className="product-grid">{filtered.map(i=><Card key={i.id} item={i}/>)}</div>:<div className="empty"><h2>No gifts found</h2><p>Try another search or explore all categories.</p><button onClick={()=>{setCategory('');setQuery('')}}>Clear filters</button></div>}</section></main>:
 page==='listing'?<main className="shop listing-detail"><a href="/collection">← Collections</a>{!ready?<p role="status">Loading gift…</p>:item?<div className="listing-detail-grid"><img className="demo-detail-image" src={item.image} alt={item.title}/><section className="listing-detail-info"><p className="eyebrow">{item.category}</p><h1>{item.title}</h1><div className="listing-prices"><strong>{formatPrice(item.price)}</strong></div><p className="muted">Sample product · Frontend preview</p><h2>About this gift</h2><p className="description">{item.description}</p><p className="description">This illustration and product are provided for demonstration. Shop links will appear when real listings are added.</p><a className="primary banner-button" href="/contact">Ask about a gift</a></section></div>:<div className="empty"><h1 className="catalog-heading">Gift not found</h1><a href="/collection">Explore the collection →</a></div>}</main>:
 <main className="info-page"><p className="eyebrow">GIFTSBYARTISANS</p><h1>{page==='contact'?'Contact us':page==='wholesale'?'Wholesale inquiry':'Shop policies'}</h1>{page==='policies'?content.policies.map(p=><details className="policy" id={'policy-'+p.id} key={p.id}><summary>{p.title}</summary><p>{p.text}</p></details>):<><p>{page==='contact'?'Have a question about a gift or an order? Send us a message.':'Interested in gifts for your store, team, or event? Tell us what you have in mind.'}</p><InquiryForm kind={page}/></>}</main>}<ShopFooter content={content}/></>;
}
function InquiryForm({kind}:{kind:'contact'|'wholesale'}){const [status,setStatus]=useState('');function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;try{const entries=JSON.parse(localStorage.getItem('gifts-demo-inquiries')||'[]');localStorage.setItem('gifts-demo-inquiries',JSON.stringify([...entries,{kind,...Object.fromEntries(new FormData(form)),createdAt:new Date().toISOString()}]));setStatus('Your demo inquiry was saved in this browser. No message was sent.');form.reset();}catch{setStatus('This browser could not save your inquiry. Please allow local storage and try again.');}}return <form className="inquiry-form" onSubmit={submit}><label>Your name<input name="name" autoComplete="name" maxLength={150} required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label>{kind==='wholesale'&&<><label>Business or organization<input name="business" autoComplete="organization"/></label><label>Approximate quantity<input name="quantity" type="number" min="1"/></label></>}<label>Message<textarea name="message" rows={6} maxLength={5000} required/></label><p className="muted">Frontend demo: this inquiry stays in your browser.</p><p role="status">{status}</p><button className="primary">Save demo inquiry</button></form>}
